openapi: 3.0.1
info:
  title: ESN-SA2-iter4-Map (Chien-Hung Wang)
  description: >-
    This is a API documents for ESN application - iteration 4 –– Map (Chien-Hung Wang)
  # termsOfService:
  # contact:
  # license:
  version: 1.0.0-oas3
# externalDocs:
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/cmusv-fse-s21-sa2/ESN-SA2/1.0.0-oas3
  - url: https://s21esn-sa2.herokuapp.com/
    description: Heroku server
tags:
  - name: map
    description: Operations about map
    # externalDocs:
    #   description: Find out more about our store
    #   url: 'http://swagger.io'
    
security:
  - cookieAuth: []
    
paths:
  /map/areas:
    get:
      tags:
        - map
      summary: Retrieve all previously marked dangerous areas
      description: Retrieve all previously marked dangerous areas
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum:
                      - 0
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Area'
                      
        '401':
          $ref: '#/components/responses/UnauthorizedError'
                      
  
  /map/area/{username}:
    post:
      tags:
        - map
      summary: Mark a dangerous area
      description: Mark a dangerous area
      parameters:
        - name: username
          in: path
          description: The user who marked the area
          required: true
          explode: true
          schema:
            type: string
      requestBody:
        description: Retrieved from user input
        content:
          application/json:
              schema:
                type: object
                properties:
                  level:
                    type: string
                  note:
                    type: string
                  coords:
                    type: array
                    items:
                      type: object
                      properties:
                        lat: 
                          type: string
                        lng:
                          type: string
      
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum:
                      - 0
                  message:
                    type: string
        
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        
          
          
    
    put:
      tags:
        - map
      summary: Update a dangerous area
      description: Update dangerous area
      parameters:
        - name: username
          in: path
          description: The user who updated the area
          required: true
          explode: true
          schema:
            type: string
      requestBody:
        description: Retrieved from user input
        content:
          application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  level:
                    type: string
                  note:
                    type: string
      
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum:
                      - 0
                  message:
                    type: string
        
        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
        '404':
          description: Marked area not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum:
                      - -1
                  message:
                    type: string
  
  /map/area/{areaId}:
    delete:
      tags:
        - map
      summary: Remove a dangerous area 
      description: Remove a dangerous area 
      parameters:
        - name: areaId
          in: path
          description: The id of the dangerous area to remove
          required: true
          explode: true
          schema:
            type: string
      
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum:
                      - 0
                  message:
                    type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
        '404':
          description: Marked area not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum:
                      - -1
                  message:
                    type: string
          
    
          
          

  
  
                        
      
components:
  schemas:
    Area:
      type: object
      properties:
        _id:
          type: string
        markBy:
          type: string
        updateBy:
          type: string
        level:
          type: string
        note:
          type: string
        coords:
          type: array
          items:
            type: object
            properties:
              lat: 
                type: string
              lng:
                type: string
            
  
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                enum:
                  - -1
              message:
                type: string
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
    # petstore_auth:
    #   type: oauth2
    #   flows:
    #     implicit:
    #       authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    #       scopes:
    #         'write:pets': modify pets in your account
    #         'read:pets': read your pets
    # api_key:
    #   type: apiKey
    #   name: api_key
    #   in: header